- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello File
      file:
        path: /tmp/hello.world
        state: touch

